import { VodSource } from "@/types/drama";

// 可导入的预设VOD源配置（纯数据，客户端安全）
export const presetVodSources: VodSource[] = [
  {
    key: "rycjapi",
    name: "如意资源站",
    api: "https://cj.rycjapi.com/api.php/provide/vod",
    playUrl: "https://ryplayer.com?url=",
    type: "json",
  },
  {
    key: "hongniuzy",
    name: "红牛资源",
    api: "https://www.hongniuzy2.com/api.php/provide/vod/from/hnm3u8",
    playUrl: "https://www.hnjiexi.com/m3u8/?url=",
    type: "json",
  },
  {
    key: "huyajx",
    name: "虎牙资源",
    api: "https://www.huyaapi.com/api.php/provide/vod/from/hym3u8/at/json",
    playUrl: "https://huyajx.com/play/?url=",
    type: "json",
  },
  {
    key: "iqiyizy",
    name: "爱奇艺资源【国内直连】",
    api: "https://www.iqiyizyapi.com/api.php/provide/vod",
    playUrl: "https://www.iqiyizyjx.com/?url=",
    type: "json",
  },
  {
    key: "dbzy",
    name: "豆瓣资源",
    api: "https://caiji.dbzy5.com/api.php/provide/vod/from/dbm3u8/at/josn",
    playUrl: "https://www.dbjiexi.com:966/jx/?url=",
    type: "json",
  },
  {
    key: "hhzy",
    name: "豪华资源 ",
    api: "https://hhzyapi.com/api.php/provide/vod/from/hhm3u8/at/json",
    playUrl: "https://hhjiexi.com/play/?url=",
    type: "json",
  },
  {
    key: "moduzy",
    name: "魔都资源网",
    api: "https://www.mdzyapi.com/api.php/provide/vod",
    playUrl: "https://jiexi.modujx01.com/?url=",
    type: "json",
  },
  {
    key: "subocj",
    name: "速播资源",
    api: "https://subocj.com/api.php/provide/vod/from/subm3u8/at/json",
    playUrl: "https://subojiexi.com/play/?url=",
    type: "json",
  },
  {
    key: "ikunzyapi",
    name: "iKun资源",
    api: "https://ikunzyapi.com/api.php/provide/vod",
    playUrl: "https://www.ikdmjx.com/?url=",
    type: "json",
  },
  {
    key: "jinyingzy",
    name: "金鹰资源",
    api: "https://jyzyapi.com/provide/vod/from/jinyingm3u8/at/json",
    playUrl: "https://hd.iapijy.com/play?url=",
    type: "json",
  },
  {
    key: "xinlangzy",
    name: "新浪资源",
    api: "https://api.xinlangapi.com/xinlangapi.php/provide/vod/from/xlm3u8/at/xml/",
    playUrl: "https://www.xinlangjiexi.com/m3u8/?url=",
    type: "xml",
  },
  {
    key: "guangsuzy",
    name: "光速资源",
    api: "https://api.guangsuapi.com/api.php/provide/vod/from/gsm3u8/at/xml/",
    playUrl: "https://www.gszyv.com/m3u8/?url=",
    type: "xml",
  },
  {
    key: "shanhaizy",
    name: "山海资源",
    api: "https://zy.sh0o.cn/api.php/provide/vod/at/json",
    playUrl: "https://im1907.top/?jx=",
    type: "json",
  },
  {
    key: "maoyanzy",
    name: "猫眼资源",
    api: "https://api.maoyanapi.top/api.php/provide/vod/from/mym3u8/at/json",
    playUrl: "https://jx.maoyanjx.top/player/?url=",
    type: "json",
  },
  {
    key: "maotaizy",
    name: "茅台资源",
    api: "https://caiji.maotaizy.cc/api.php/provide/vod/from/mtm3u8/at/josn",
    playUrl: "https://www.mtjiexi.cc:966/?url=",
    type: "json",
  },
  {
    key: "ukuapi88",
    name: "U酷资源网",
    api: "https://api.ukuapi88.com/api.php/provide/vod",
    playUrl: "https://api.ukubf.com/m3u8/?url=",
    type: "json",
  },
  {
    key: "baofengziyuan",
    name: "暴风资源",
    api: "https://bfzyapi.com/api.php/provide/vod",
    playUrl: "https://vip.vipuuvip.com/?url=",
    type: "json",
  },
  {
    key: "360zy",
    name: "360资源",
    api: "https://360zy.com/api.php/provide/vod",
    playUrl: "https://www.360jiexi.com/player/?url=",
    type: "json",
  },
  {
    key: "wolongzy",
    name: "卧龙资源",
    api: "https://collect.wolongzy.cc/api.php/provide/vod/",
    playUrl: "https://jx.wolongzywcdn.com:65/m3u8.php?url=",
    type: "json",
  },
  {
    key: "jszyapi",
    name: "极速资源",
    api: "https://jszyapi.com/api.php/provide/vod/from/jsm3u8/at/json",
    playUrl: "https://jsjiexi.com/play/?url=",
    type: "json",
  },
];
